def print_help(manager, Colors):
    """打印帮助信息"""
    print(f"\n{Colors.BOLD}可用命令:{Colors.RESET}")
    print(f"  {Colors.GREEN}n / next{Colors.RESET}: 下一页")
    print(f"  {Colors.GREEN}p / prev{Colors.RESET}: 上一页")
    print(f"  {Colors.GREEN}g / goto{Colors.RESET}: 跳转到指定页")
    print(f"  {Colors.GREEN}a / add{Colors.RESET}: 添加服务器")
    print(f"  {Colors.GREEN}d / delete{Colors.RESET}: 删除服务器")
    print(f"  {Colors.GREEN}u / update{Colors.RESET}: 更新服务器信息")
    print(f"  {Colors.GREEN}s / save{Colors.RESET}: 保存服务器列表")
    print(f"  {Colors.GREEN}r / refresh{Colors.RESET}: 刷新当前页")
    print(f"  {Colors.GREEN}clear / clearcache{Colors.RESET}: 强制清除所有缓存")
    print(f"  {Colors.GREEN}o / sort{Colors.RESET}: 排序服务器")
    print(f"  {Colors.GREEN}c / pagesize{Colors.RESET}: 更改每页显示数量 (当前: {manager.page_size})")
    print(f"  {Colors.GREEN}f / filter{Colors.RESET}: 筛选服务器类型")
    print(f"  {Colors.GREEN}players / player <序号>{Colors.RESET}: 查看指定服务器的完整玩家列表")
    print(f"  {Colors.GREEN}info / detail <序号>{Colors.RESET}: 查看指定服务器的详细信息")
    print(f"  {Colors.GREEN}monitor / mon <序号>{Colors.RESET}: 监控指定服务器的状态变化")
    print(f"  {Colors.GREEN}monitor / mon <序号1> <序号2> ...{Colors.RESET}: 同时监控多个服务器的状态变化")
    print(f"  {Colors.GREEN}scan / scancommon{Colors.RESET}: 扫描IP/域名下的Minecraft服务器端口")
    print(f"  {Colors.GREEN}scanall / scanfull{Colors.RESET}: 扫描IP/域名下的所有端口 (1-65535)")
    print(f"  {Colors.GREEN}h / help{Colors.RESET}: 显示帮助")
    print(f"  {Colors.GREEN}q / quit{Colors.RESET}: 退出")

    print(f"\n{Colors.BOLD}监控功能说明:{Colors.RESET}")
    print(f"  • 实时监控服务器状态变化")
    print(f"  • 检测玩家加入/退出事件和玩家数量变化")
    print(f"  • 按 '+' 增加刷新间隔，'-' 减少刷新间隔")
    print(f"  • 按 'r' 手动刷新，'t' 切换事件排序方式")
    print(f"  • 按 'l' 查看完整日志，支持滚动和导出")
    print(f"  • 按 'q' 或 Ctrl+C 退出监控模式")

    input(f"\n{Colors.CYAN}按回车键继续...{Colors.RESET}")
